# Travis-CI Build for bpki
# see travis-ci.org for details

language: generic

os: linux
dist: trusty
sudo: required

before_install:
  - sudo apt-get install -y --no-install-recommends
      texlive-base texlive-latex-base texlive-latex-extra 
      texlive-latex-recommended texlive-generic-extra
      texlive-fonts-recommended texlive-generic-recommended
      texlive-fonts-extra texlive-lang-cyrillic 

script:
  - cd spec
  - pdflatex -interaction=nonstopmode -halt-on-error bpki.tex
  - pdflatex -interaction=nonstopmode -halt-on-error bpki.tex
  - cd ..

deploy:
  provider: releases
  api_key: 
    secure: FQxyMiOmhrZzI3taVGejL7wlDG24DrsZFODTLtB/hAExBQecf7T6wPEQVhiRQpWDL8v67nXaEpFSwhbQbyM1KKDXt3g0uwzq3F6KbBVfiAnCZXkj+OvUM8xZVh5rDF4kBDfh2xrUuVX8QG8dcGcEKM+CvcVCi9yL2cNekTsuxn3QVoZifW3cLtaEMUjkm67BhVeapNMMPgL/QSO1PAl81o7zyvYyPGDCGdt/8yowKhpTxarIrwWtA+/ILcEkiQiK8JYH3QOvLENAlooJTRbOB1Hvkv2xdKMYo1/bnwMawMpYIJLJ/nb6Av5FDCB8gPo4vHZ/JgSo5//7LYMWyiRsacKuIOK66Te+1LWOQ5akHpOGUgrToFKmILlj/4SUBrhfOdUK5kIjb0YG2Nn83Lq4JE7RBGWz3VKEKitl0lcJXcPrtb+mOcmkrFupv+u0ifkwsDJElGUdiKgKYBcW8eZ1iNCTTyUugT8pC7whAm2/8C8G1/sgjRydNNsFytvA+KpRIS+/nA5ncmaGvY7gn66+B9hJ0jBGlePPwWWw3v6h8xcA73MPtbZQSS44s74pfSODgmEPRy/HyBV5G18NfR7PThykTzHI8jLwU3dnWxmx7kjAWwZJeTq7bzHsuLWeIazXu62VYSxfjo9eQ2Gy8A5Y+h8S80e/ANCuiKFmPDz0ZKM=
  file: spec/bpki.pdf
  skip_cleanup: true
  overwrite: true
  on:
    repo: bcrypto/bpki
    branch: master
    tags: true